[package]
name = "rust_quantum_mathematics"
version = "0.1.1"
edition = "2022"
email = "RXRD@tutanota.com"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
